### ISSUE TITLE
SeparateTextures Option is not work when convert to glb

### ISSUE THREAD

**Issue by weilichuang** [godotengine/FBX2glTF#18]
Use the latest version of the converter convert a model(contain textures)
`FBX2glTF.exe -i .\test.fbx -o test.glb --separate-textures`
or
`FBX2glTF.exe -i .\test.fbx -o test.glb -b`

the `test.glb` still contain textures.

If I try convert to glft
`FBX2glTF.exe -i .\test.fbx -o test.gltf --e`
It will save textures separately.

[test.zip](https://github.com/V-Sekai/FBX2glTF/files/8889548/test.zip)

**Comment by fire** [comment]
I thought that the .glb extension means all images are packed into the single glb.

Blender does the same design.

![image](https://user-images.githubusercontent.com/32321/187048489-3993fe8c-f663-4849-bcbe-6cd066116add.png)

1. glb as a single file
2. gltf as a single file but with base64
3. gltf with textures separately.

Not sure how to resolve.

**Comment by fire** [comment]
As far as I know this is the expected behavior. Making `.glb` write external textures is possible but it wouldn't be a common `.glb`.
