### ISSUE TITLE
FbxSkeleton should create empty skins with all of the bones.

### ISSUE THREAD

**Issue by lyuma** [godotengine/FBX2glTF#19]
See here for a description:
https://github.com/godotengine/godot/issues/60854#issuecomment-1153095865
and here:
https://github.com/godotengine/godot/issues/62275#issuecomment-1162463175

FBX knows that the nodes are part of a skeleton because they have an FbxSkeleton attached. Hence, FBX2glTF should detect this case and create a dummy glTF skin like discussed in this blender gltf io issue here:
https://github.com/KhronosGroup/glTF-Blender-IO/issues/822

(This functionality that allows you to convert in Blender is therefore actually quite new, in Blender 3.2 )

**Comment by fire** [comment]
This is still wanted.
