### ISSUE TITLE
How different is this compared to the original facebookincubator repo?

### ISSUE THREAD

**Issue by Apidcloud** [godotengine/FBX2glTF#29]
Hello!

Not sure if this is the place to ask such question, so feel free to point me in the right direction here.

I recently started using this repo, after finding it was a more up-to-date version of the original facebookincubator fbx2gltf repo. But now I'm wondering if the notes in the original README about certain improvements and not supported features are already taken into consideration in this fork. I'm asking because the README from this fork doesn't have all the info the original had.

In essence, I would like to know what's not supported when converting from fbx to gltf using the latest release ([v0.13.0-p1](https://github.com/godotengine/FBX2glTF/releases/tag/v0.13.0-p1)). Do you happen to have a list or some info on it?

Thank you for your time and your awesome work!

**Comment by fire** [comment]
The short answer is it has been several years since we diverged.

I don't remember all the changes. One would have to go through the last Facebook changes and patch by patch check.

If you have specific inquires I can try to find out.

**Comment by akien-mga** [comment]
> I don't remember all the changes. One would have to go through the last Facebook changes and patch by patch check.

There's no change in the Facebook version  that would be missing here. The upstream development stopped around the time you forked it.

The only FB commit which isn't in this fork is just removing the AppVeyor config: https://github.com/facebookincubator/FBX2glTF/commit/739ee5db94b0ca9eabe2b6ed92f32d13175072a3

**Comment by Apidcloud** [comment]
Thank you both for taking the time to reply to this. Since there’s nothing from the original repo missing in this one, I guess can now rephrase the question. Should I still take into consideration the original README at all, other than, perhaps, the cli options?
And, are there known limitations when converting from fbx to gltf? I don’t know enough about the formats themselves to understand whether they are 100% compatible or not in the first place. Obj to gltf seems to have some limitations, for instance.

On 21 Jan 2023, at 17:46, Rémi Verschelde ***@***.***> wrote:

﻿

I don't remember all the changes. One would have to go through the last Facebook changes and patch by patch check.

There's no change in the Facebook version that would be missing here. The upstream development stopped around the time you forked it.

The only FB commit which isn't in this fork is just removing the AppVeyor config: ***@***.***<https://github.com/facebookincubator/FBX2glTF/commit/739ee5db94b0ca9eabe2b6ed92f32d13175072a3>

**Comment by fire** [comment]
We defaulted to bake30fps. We attempted to solve pivots in gltf but it failed, so that part in the same state as the parent repo. The default of non pbr is still the same I think.

**Comment by fire** [comment]
The build system works. I converted the original build system to something that runs smoothly.

**Comment by Apidcloud** [comment]
Yup. I found this fork because I was trying to build the original within a node-alpine docker image but had some issues that guided me here. When I tried this one it worked pretty well. Is there any known limitation regarding textures or animations?

On 21 Jan 2023, at 11:34 pm, K. S. Ernest (iFire) Lee ***@***.******@***.***>> wrote:



The build system works. I converted the original build system to something that runs smoothly.

**Comment by fire** [comment]
We changed the default to 8 bone weights max and to png.

**Comment by Apidcloud** [comment]
Thanks again! I'll reopen if meanwhile we have some specific question.
